# Generated by Django 3.0.3 on 2020-06-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=500)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
